### PR TITLE
feat: add "connect with alby" button

### LINKED ISSUE #2: Use alby-js-sdk for creating NWC connection string
Just click a button and it will launch nwc and generate a new NWC url for you. I will try create a PR for this!

### PR DESCRIPTION
**Pull request by rolznz**
Fixes https://github.com/futurepaul/zapple-pay-frontend/issues/2

Adds a more user-friendly way for users to get a NWC url.

image

### CODE REVIEW

**Comment by futurepaul** [comment]
dangit lol this is really good but I want to use zapple pay to shill mutiny! going to close for now but will think on the best way to be fair to multiple wallets

**Comment by rolznz** [comment]
@futurepaul the more people that use Zapple Pay the more will be exposed to Mutiny.

We have been planning to make a nostr wallet connect javascript library that provides some "Connect Wallet" components - Mutiny could be listed first as the recommended wallet, followed by other options. What do you think? would you be willing to integrate with a library like this?

image

image

**Comment by futurepaul** [comment]
this looks really cool! I'll def keep it in mind, will leave as-is for now but I appreciate it for sure

**Comment by benthecarman** [comment]
@rolznz i dont think the button will even work. Alby nwc strings are invalid and do not follow the spec, you guys would need to fix that first

**Comment by rolznz** [comment]
@benthecarman we have an [open PR](https://github.com/getAlby/nostr-wallet-connect/pull/105) - I will try to push it to get merged. Thanks!

**Pull request closed without merging**
